baseURL = "https://testinghanumansite.github.io/"
languageCode = "en-us"
title = "Hanuman Chalisa Hindi"
theme = "hugo_theme_robust"
backgroundColor="orange"
Paginate = "10"
PaginatePath = "page"
googleAnalytics = "UA-99105092-1" # Optional
